### PR TITLE
[Trivial] Updated Dodo minor version in Setup section

### PR DESCRIPTION
**Pull request by le4ker**

### CODE REVIEW

**Comment by evgenyneu** [comment]
Hi, @PanosSakkos, thanks for the change. Just to make sure I understand what we are doing here. The '~> 2.2.1' operator will make the library auto-update to the newer version only when the 3rd "patch" version number changes. For example, from 2.2.1 to 2.2.2. But it will not auto-update to the new "minor" version, to 2.3.0, for example. Is that correct and what you intended?

**Comment by evgenyneu** [comment]
Note that when we make the API breaking changes to the library we change the first "major" digit of the version. From 2.2.1 to 3.0.0 for example.

**Comment by le4ker** [comment]
You're welcome! Good stuff by the way! 👏 

I followed the setup instructions and I noticed that the version that was mentioned was on 2.2, while the version on CocoaPods was 2.2.1. 
Since I wanted the latest version I set it to 2.2.1 in my Podfile, and I thought that the same should be done in the documentation, because as a first time user of the library you will always want the latest stable version, right? 😄

**Comment by evgenyneu** [comment]
Thank you. I see what you intended to do now.

If you are using the so called "optimistic version" operator "~>" it will load version 2.2.1 if you specify "~> 2.2" in the Podfile. It will also load future updates automatically, like 2.2.2, 2.2.3, even 2.3.0 and 2.4.8. But it will not load major version updates like 3.1.0 (the first version number is changed), because this is were the library changes that can break your app can be introduced.

If it sounds confusing, and I know it can be, there is more information here

Semantic versioning standard: http://semver.org/

Version number syntax used in CocoaPods: https://guides.cocoapods.org/using/the-podfile.html

It is up to you which version to load in your Podfile but I would keep the two digits optimistic version "~> 2.2" in the readme because it means updating the library to all latest non-breaking changes. Do you think it is a good idea?

**Comment by le4ker** [comment]
I see! Great, thanks for the cocoapods lesson! 😄

**Comment by le4ker** [comment]
I read again your comment because I was planning to fix all the pod files in the projects that I'm working on, since I was using everywhere the optimistic version operator in combination with the full version (i.e. 2.2.1).

> It is up to you which version to load in your Podfile but I would keep the two digits optimistic version "~> 2.2" in the readme because it means updating the library to all latest non-breaking changes. Do you think it is a good idea?

Definitely! 😄 

Keep up the great work for the community! 👏

**Comment by evgenyneu** [comment]
Thank you, have a great day.

**Pull request closed without merging**
